import pandas as pd
import os
import requests
from tqdm import tqdm
import time

# Official SAS Path for DR17 ASPCAP spectra
BASE_URL = "https://data.sdss.org/sas/dr17/apogee/spectro/aspcap/dr17/synspec_rev1/{telescope}/{field}/aspcapStar-dr17-{apid}.fits"
DOWNLOAD_DIR = "data/raw_spectra/"

def download_spectra():
    if not os.path.exists(DOWNLOAD_DIR): 
        os.makedirs(DOWNLOAD_DIR)
    
    # Ensure this matches the file generated by your catalog_manager.py
    csv_path = "data/golden_sample.csv" 
    if not os.path.exists(csv_path):
        print(f"Error: {csv_path} not found!")
        return

    df = pd.read_csv(csv_path)
    
    print(f"Starting download of {len(df)} spectra...")
    for index, row in tqdm(df.iterrows(), total=len(df)):
        # Construct the URL using the correct column names from our CSV[cite: 3]
        url = BASE_URL.format(
            telescope=row['TELESCOPE'],
            field=row['FIELD'],
            apid=row['APOGEE_ID']
        )
        
        filename = f"aspcapStar-dr17-{row['APOGEE_ID']}.fits"
        filepath = os.path.join(DOWNLOAD_DIR, filename)
        
        # Skip if already downloaded (saves bandwidth!)
        if not os.path.exists(filepath):
            try:
                # Increased timeout for your 50 KB/s connection
                response = requests.get(url, timeout=30) 
                if response.status_code == 200:
                    with open(filepath, 'wb') as f:
                        f.write(response.content)
                else:
                    # Log the failed ID for later troubleshooting
                    with open("download_errors.log", "a") as log:
                        log.write(f"{row['APOGEE_ID']}: HTTP {response.status_code}\n")
            
            except Exception as e:
                print(f"\nError downloading {row['APOGEE_ID']}: {e}")
                # Brief pause to let the connection stabilize if it flickers
                time.sleep(1)

if __name__ == "__main__":
    download_spectra()